# Generated by Django 5.1 on 2024-09-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='option_name',
            new_name='option_text',
        ),
        migrations.RemoveField(
            model_name='customerfeedback',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_text',
            field=models.TextField(default='Text', max_length=100),
        ),
        migrations.RemoveField(
            model_name='customerresponse',
            name='selected_option',
        ),
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='home.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('BigText', 'Big Text'), ('Radio', 'Radio Button'), ('Checkbox', 'Checkbox')], max_length=10),
        ),
        migrations.AddField(
            model_name='customerresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.options'),
        ),
    ]
