# Generated by Django 5.1 on 2024-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_option_name_options_option_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='option_text',
            new_name='option_name',
        ),
        migrations.RemoveField(
            model_name='customerresponse',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_text',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='question',
            field=models.ManyToManyField(to='home.questions'),
        ),
        migrations.AddField(
            model_name='customerresponse',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='home.options'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default='Text', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('BigText', 'BigText'), ('Radio', 'Radio'), ('Checkbox', 'Checkboz')], default='Text', max_length=100),
        ),
    ]
