# Generated by Django 5.1 on 2024-09-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_option_text_options_option_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerresponse',
            old_name='selected_options',
            new_name='selected_option',
        ),
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='home.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('BigText', 'BigText'), ('Radio', 'Radio'), ('Checkbox', 'Checkbox')], default='Text', max_length=100),
        ),
    ]
