# Generated by Django 5.1 on 2024-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_selected_options_customerresponse_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='title',
            field=models.CharField(default='Gernal Survey', max_length=255),
        ),
    ]
